# Generated by Django 3.0.7 on 2020-06-21 09:00

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='capacity',
        ),
        migrations.AddField(
            model_name='service',
            name='maxCapacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('CL', 'Clinic'), ('HS', 'Hair Salon'), ('RE', 'Restaurant'), ('SH', 'Shop')], default='SH', max_length=2),
        ),
        migrations.CreateModel(
            name='CapacityTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=48, size=8)),
                ('tue', django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=48, size=8)),
                ('wed', django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=48, size=8)),
                ('thu', django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=48, size=8)),
                ('fri', django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=48, size=8)),
                ('sat', django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=48, size=8)),
                ('sun', django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=48, size=8)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Service')),
            ],
        ),
    ]
