# Generated by Django 3.0.6 on 2020-06-28 14:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('tue', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('wed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('thu', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('fri', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('sat', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('sun', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='capacitytable',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='capacityTable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_capacity', to='backend.CapacityTable'),
        ),
        migrations.AddField(
            model_name='service',
            name='placeId',
            field=models.TextField(default='ChIJFzzD4oqpQjQRQhKQwn4ydLM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='popularTimes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_popular_times', to='backend.PopularTimes'),
        ),
    ]
