# Generated by Django 3.0.6 on 2020-06-21 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200621_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='owner',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='service',
            new_name='provider',
        ),
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_services', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
