# Generated by Django 3.0.6 on 2020-06-29 16:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200628_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=24), default=[], size=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='populartimes',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='populartimes',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='populartimes',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='populartimes',
            name='sun',
        ),
        migrations.RemoveField(
            model_name='populartimes',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='populartimes',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='populartimes',
            name='wed',
        ),
        migrations.RemoveField(
            model_name='service',
            name='capacityTable',
        ),
        migrations.AddField(
            model_name='populartimes',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=24), default=[], size=7),
        ),
        migrations.AlterField(
            model_name='service',
            name='popularTimes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_popular_times', to='backend.PopularTimes'),
        ),
        migrations.DeleteModel(
            name='CapacityTable',
        ),
        migrations.AddField(
            model_name='service',
            name='freeSlot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_capacity', to='backend.FreeSlot'),
        ),
    ]
