# Generated by Django 3.0.6 on 2020-06-29 16:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200630_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeslot',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=24), default=list, size=7),
        ),
        migrations.AlterField(
            model_name='populartimes',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=24), default=list, size=7),
        ),
    ]
