# Generated by Django 3.0.6 on 2020-06-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200621_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isProvider',
            field=models.BooleanField(default=False),
        ),
    ]
