# Generated by Django 3.0.6 on 2020-06-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_user_isprovider'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
