# Generated by Django 3.0.6 on 2020-06-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200622_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='p001@test.com', max_length=255),
            preserve_default=False,
        ),
    ]
